# /boot/loader.conf @Dr.Deep

# Kernel
kernels="kernel"

ahci_load="YES"
coretemp_load="YES"
machdep.hyperthreading_allowed="1"

# secadm
secadm_load="YES"

# ZFS root
zfs_load="YES"
vfs.root.mountfrom="zfs:zfs/ROOT/default"
hw.usb.no_boot_wait="1"
#vfs.zfs.arc_min="1M"
#vfs.zfs.arc_max="32M"

# graphical bootloader settings
beastie_disable="YES"	# no boot screen
autoboot_delay="2"	# delay
efi_max_resolution="1920x1080x32"

# TCP cubic is modern
cc_cubic_load="YES"

# increase entropy pool size
kern.random.fortuna.minpoolsize="128"

# user-mode access to hardware-accelerated cryptography
cryptodev_load="YES"

# user-mode access to hardware-accelerated cryptography
cryptodev_load="YES"

# cryptographic GEOM class
geom_eli_load="YES"

# disallow distructive DTrace
security.bsd.allow_destructive_dtrace=0

#
kern.geom.label.disk_ident.enable="0"
kern.geom.label.gptid.enable="0"

# microcode
cpu_microcode_load="YES"
cpu_microcode_name="/boot/firmware/intel-ucode.bin"

# test for rtw88
#compat.linuxkpi.skb.mem_limit=1

# intel graphic driver
lindebugfs_load="YES"
#if_rtw88_load="YES"
i915kms_load="YES"
hw.drm.debug=0
hw.i915kms.enable_dpcd_backlight=1

# exfat fusefs
fusefs_load="YES"

# power saving: "per-core instead of per-package frequency scaling"
machdep.hwpstate_pkg_ctrl=0

# An indirect result of increasing the interface queue is the buffer acts like
# a large TCP initial congestion window (init_cwnd) by allowing a network stack
# to burst packets at the start of a connection. Do not to set to zero(0) or
# the network will stop working due to "no network buffers" available. Do not
# set the interface buffer ludicrously large to avoid buffer bloat.
net.link.ifqmaxlen="2048"  # (default 50)

# Enable the optimized version of soreceive() for stream (TCP) sockets.
# soreceive_stream() only does one sockbuf unlock/lock per receive independent
# of the length of data to be moved into the uio compared to soreceive() which
# unlocks/locks per *mbuf*. soreceive_stream() can significantly reduced CPU
# usage and lock contention when receiving fast TCP streams. Additional gains
# are obtained when the receiving application is using SO_RCVLOWAT to batch up
# some data before a read (and wakeup) is done.
net.inet.tcp.soreceive_stream="1"  # (default 0)

#
hw.syscons.bell=0
hw.usb.no_shutdown_wait=1
hw.nvme.use_nvd=1
#hardening.elf_pie_only=1
