bsdjlap {
	path		= "/zfs/bsdjlap";
	host.hostname	= "bsdjlap";
	devfs_ruleset	= "5";  # bsdjlap ruleset
	exec.start = "/bin/sh /etc/rc";
	exec.stop = "/bin/sh /etc/rc.shutdown";
	persist; # persistent
}
