# /etc/make.conf @Dr.Deep

# ccache
WITH_CCHACHE_BUILD=yes
CCACHE_DIR=/usr/ccache
CCACHE_BIN=/usr/local/bin/ccache
#CCACHE_SLOPPINESS=file_macro,time_macro
CCACHE_MAXSIZE=10G
CCACHE_COMPILER=clang

# Native
CPUTYPE			?= native
COMMON_FLAGS		=  -O3 -pipe -march=native -mtune=native -maes -mmmx -mpclmul -mpopcnt -mrdrnd -msha -msse4.1 -msse4.2 -mssse3 \
#-funroll-loops -ftree-vectorize -mprefer-vector-width=128 \
-fzero-call-used-regs=used -fomit-frame-pointer #-fstack-protector-strong -fstack-clash-protection
# -O2/-O3 , -flto , -fopenmp ,  -flto -ffat-lto-objects

#-funroll-loops -falign-functions -mllvm -enable-partial-inlining -mllvm -enable-loop-distribute
 -fzero-call-used-regs=used \
#-fvectorize -ftree-vectorize -finline-functions -mllvm --enable-memcpy-dag-opt \
#-fstack-check -fomit-frame-pointer -fstack-protector-strong
# -DNDEBUG ?
# -D_FORTIFY_SOURCE=2

#RUSTFLAGS="-L /usr/local/lib/gcc13"
CFLAGS			+= ${COMMON_FLAGS}
CXXFLAGS		+= ${COMMON_FLAGS}
#LDFLAGS			+= -Wl,--strip-all -O2 -z relro -z now
# -flto -fuse-ld=lld -Wl,--threads=4
#MAKEOPTS		= -j8


#USE_HARDENING		+= zeroreg
#DEFAULT_VERSIONS	+= ssl=libressl-devel # openssl is unsafe
OPTIONS_UNSET		+= EXAMPLES DOCS CUPS GSSAPI AVX AVX2 JACK APIDOCS APIDOC DOXYGEN HTMLDOCS INFO PDFDOCS TEST ZSH
OPTIONS_SET		+= MAN MANPAGES NLS X11 WAYLAND DBUS GSSAPI_NONE OPTIMIZATIONS OPTIMIZED_CFLAGS OPTIMIZED_FLAGS PTHREAD PTHREADS THREADSAFE OPENMP CPU_OPTS SSE SSE2 SSE3 SSSE3 SSE41 SSE42 FFMPEG AVAHI GPL GPL3 NONFREE KQUEUE BASH ICU OPENSSL GMP SIMD PIPEWIRE PULSEAUDIO
