# /etc/make.conf @Dr.Deep

COMMON_FLAGS		=  -march=native -mtune=native -pipe -ffast-math -funroll-loops -falign-functions -fzero-call-used-regs=used -flto -fvectorize -ftree-vectorize -finline-functions -fstack-check -fcf-protection
CFLAGS			+= ${COMMON_FLAGS}
CXXFLAGS		+= ${COMMON_FLAGS}
LDFLAGS			+= -Wl,--strip-all --as-needed -O2 -z relro -z now
MAKEOPTS		= -j4

# LibreSSL
DEFAULT_VERSIONS	+= ssl=libressl-devel
# weil freebsd openssl ist sehr
