#!/bin/sh
# /etc/rc.conf @Dr.Deep

#
# System Configuration
#

# Kernel Modules
kld_list="${kld_list} i915kms acpi_ibm acpi_video vmm if_tap nmdm"

# Hostname
hostname="bsdlap"

# Console Options
rc_info="YES"
rc_startmsgs="NO"
keymap="de.kbd"
keyrate="fast"
moused_nondefault_enable="NO"

# no kernel dumps
dumpdev="NO"

# Secure-Level
#kern_securelevel_enable="YES"
#kern_securelevel="-1"

# Run the audit Daemon
#auditd_enable="NO"


#
# Services
#

# ZFS
zfs_enable="YES"

# Time Sync
ntpd_enable="NO"
openntpd_enable="YES"

# Desktop Services
dbus_enable="YES"
seatd_enable="YES"

# Powerd
powerd_enable="YES"
powerd_flags="-a max -b hiadaptive"

# System Logger
syslogd_enable="YES"
syslogd_flags="-ss"

# virt-manager
libvirtd_enable="YES"

#
# Network
#

# Default Firewall
firewall_enable="YES"
firewall_type="workstation"
firewall_logging="YES" 
firewall_logdeny="YES"
firewall_coscripts="/usr/local/etc/openvpn/firewall.sh"

# Wifi Connection
wlans_rtwn0="wlan0"
ifconfig_wlan0="ether d8:cf:bf:a8:ff:f1 WPA DHCP"
create_args_wlan0="country DE regdomain ETSI"

# we use dhcpcd
dhclient_program="/usr/local/sbin/dhcpcd"
dhclient_flags="-S domain_name_servers=1.1.1.1"
background_dhclient_wlan0="YES"
background_dhclient_ue0="YES"

# ProtonVPN
openvpn_enable="YES"
openvpn_if="tun tap"
openvpn_flags="--daemon protonvpn"
openvpn_configfile="/usr/local/etc/openvpn/nl-free-129.protonvpn.udp.ovpn.conf"

#
# Jails
#

smartd_enable="YES"                                         
#webcamd_enable="YES"
