# /etc/src.conf by @Dr.Deep

# CCACHE
WITH_CCACHE_BUILD=yes

WITHOUT_WERROR=yes

# Position-Independent Executable
WITH_PIE=yes

# retpoline speculative execution vulnerability mitigation
WITHOUT_RETPOLINE=yes
WITHOUT_KERNEL_RETPOLINE=yes

#WITHOUT_STACKSAFE=yes

#
#WITH_ASAN=yes
#WITH_UBSAN=yes

# 
WITH_BIND_NOW=yes

# Control-Flow-Integrity
#WITH_CFI=yes

# for LTO
#WITHOUT_CTF=1
WITH_LTOLIB=yes

# muss man net kompilieren geht auch aus den ports
WITH_TOOLCHAIN=yes
WITH_CLANG_FULL=yes
WITHOUT_LLVM_TARGET_ALL=yes
WITH_LLVM_TARGETS=host

#
KERNCONF=KIRBYBSD
WITH_MALLOC_PRODUCTION=yes
WITHOUT_LLVM_ASSERTIONS=yes

# Bloat
WITHOUT_APM=yes
#WITHOUT_NETGRAPH ?
#WITHOUT_ATM ?
WITHOUT_AUTHPF=yes
WITHOUT_AUTOFS=yes
WITHOUT_BLACKLIST=yes
WITHOUT_BLUETOOTH=yes
WITHOUT_BOOTPARAMD=yes
WITHOUT_BOOTPD=yes
WITHOUT_BSNMP=yes
WITHOUT_CALENDAR=yes
WITHOUT_MAIL=yes
WITHOUT_FLOPPY=yes
WITHOUT_FREEBSD_UPDATE=yes
WITHOUT_GAMES=yes
WITHOUT_HAST=yes
WITHOUT_HTML=yes
WITHOUT_INETD=yes
WITHOUT_KERBEROS=yes
WITHOUT_ISCSI=yes
WITHOUT_KVM_SUPPORT=yes
WITHOUT_MLX5TOOL=yes
WITHOUT_NIS=yes
#WITHOUT_NS_CACHING=yes
WITHOUT_PPP=yes
WITHOUT_RADIUS_SUPPORT=yes
WITHOUT_RBOOTD=yes
WITHOUT_TALK=yes
WITHOUT_TCP_WRAPPERS=yes
WITHOUT_TCSH=yes
WITHOUT_TFTP=yes
WITHOUT_UNBOUND=yes
WITHOUT_VI=yes
WITHOUT_NTP=yes
WITHOUT_SOURCELESS=yes
