# $FreeBSD$
#
# To disable this repository, instead of modifying or removing this file,
# create a /usr/local/etc/pkg/repos/HardenedBSD.conf file:
#
#   mkdir -p /usr/local/etc/pkg/repos
#   echo "HardenedBSD: { enabled: no }" > /usr/local/etc/pkg/repos/HardenedBSD.conf
#

hbsdsrv: {
  url: "https://vmd171781.contaboserver.net/packages/HBSD-14-STABLE-default",
  mirror_type: "none",
  signature_type: "pubkey",
  pubkey: "/etc/pkg/hbsdsrv.cert"
  enabled: yes,
  priority: 100,
}
